### ISSUE TITLE
stack overflow search

### ISSUE THREAD

**Issue by asselin** [asselin/test#1]
#Story
As a developer, I want to be able to input search queries, so that I can search Stack Overflow when I'm stuck

# Tasks
- [ ] Create a text input box
- [ ] Add a search button
- [ ] Make a call to stack overflow
